services:
  media-indexer:
    image: amitkshirsagar13/media-indexer:latest
    container_name: media_indexer
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "zbox.local:192.168.12.111"
    ports:
      - "2345:2345"
    volumes:
      # Mount configuration
      - ./config.yml:/app/config.yml

      # Mount external yt-dlp binary and folder
      - /usr/local/bin/yt-dlp:/usr/local/bin/yt-dlp:ro
      - /media/zbox/Crucial-X6/ShareMe/media/songs/target:/app/ytdlp
      - /media/zbox/Crucial-X6/ShareMe/media/songs/target/cookies-zbox.txt:/app/cookies/yt_cookies.txt:ro

      - /home/shared/services/store/mnts/vectordb:/app/data
      # Mount external media directories under /media/<mount_name>
      - /media/zbox/Crucial-X6/ShareMe/media/songs/target:/media/storage/songs
      - /media/zbox/Crucial-X6/ShareMe/media/serials/x:/media/storage/x-serials
      - /media/zbox/Crucial-X6/ShareMe/media/serials/TV Shows:/media/storage/shows
      - /media/zbox/storage/ShareMe/media/movies:/media/storage/movies
      - /media/zbox/storage/xos/x-linux/videos/xxx:/media/storage/xCollection
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped